### ISSUE TITLE
Mocking file responses

### ISSUE THREAD

**Issue by nwhite89** [apibyexample/abe-spec#6]
I have a scenario where I am generating a JS files content on the fly based on params passed to an end-point.

These params are then added to the JS File's response, currently using ABE-spec like so

``` js
{
    "description": "Generate a JS files",
    "url": "/example/js/endpoint",
    "method": "POST",
    "examples": {
        "CREATED": {
            "description": "JS file generated and returned",
            "request": {
                "url": "/example/js/endpoint",
                "queryParams": {},
                "body": {
                    "some_content": "hello, world!"
                }
            },
            "response": {
                "status": 200,
                "headers": {
                    "Content-Type": "application/javascript"
                },
                "body": "function run () { console.log('hello, world!'); }"
            }
        }
    }
}
```

**Comment by nwhite89** [comment]
love to hear some thoughts on this @txels @jedrichards @jonman @JoseKilo

**Comment by txels** [comment]
Not sure what you want the feedback on... the fact that you use a content type in the response? That looks legit to me :+1: . We already used that for CSV files I believe.

**Comment by nwhite89** [comment]
True, so the example is JS, now that can use double or single quotes. If you want to then test against the body to make sure you get the expected result, it forces the JS to be written in a certain while and also in one line.

Only other thought I could think so is possibly doing something like:

with double quotes

``` js
"body": "function run () { console.log(\"hello, world!\"); }"
```

multi line

``` js
"body": "function run () {\n console.log('hello, world!');\n}"
```

**Comment by txels** [comment]
The JSON format is well defined in this aspect. I tried with python BTW:

``` python
>>> a = { "body": """function run () {
 console.log("hello, world!");
}""" }
>>> print json.dumps(a)
{"body": "function run () {\n console.log(\"hello, world!\");\n}"}
```

**Comment by nwhite89** [comment]
I will make this into an example and close this Issue :+1:
